import {escapeHTML as e} from './render.js';
import {safeUrl,dateLabel,eventState,stale} from './v3-core.js';
const link=(url,label)=>`<a href="${e(safeUrl(url))}">${e(label)} ↗</a>`;
export function photoHTML(media,id,eager=false){
 const m=(media||[]).find(x=>x.id===id);if(!m)return '';
 const thumb=w=>m.thumbnail_base+w+'px-'+m.filename;
 return `<figure class="local-photo"><img data-fallback-src="${e(m.image_url)}" src="${e(thumb(960))}" srcset="${e(thumb(640))} 640w, ${e(thumb(960))} 960w, ${e(thumb(1280))} 1280w" sizes="(max-width: 700px) 92vw, 52vw" width="${m.width}" height="${m.height}" alt="${e(m.alt)}" loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''} decoding="async" referrerpolicy="no-referrer"><figcaption>${e(m.title)} · ${link(m.original_url,m.creator)} · ${link(m.license_url,m.license)}<span class="photo-date">Photo: ${dateLabel(m.taken)} · resized, uncropped</span></figcaption></figure>`;
}
export function communityPins(rows,venues){
 // Only explicit record-to-venue matches; never geocode from an organizer name.
 const groups=[];
 for(const venue of venues||[]){
  if(venue.verified!==true||!venue.coordinate_source||!Number.isFinite(venue.latitude)||!Number.isFinite(venue.longitude)||Math.abs(venue.latitude)>90||Math.abs(venue.longitude)>180)continue;
  const events=rows.filter(r=>r.venue_id===venue.id);
  if(events.length)groups.push({venue,events});
 }
 return groups;
}
export function venuePopupHTML(pin){
 return `<strong>${e(pin.venue.name)}</strong><p>${e(pin.venue.address)}</p><ul>${pin.events.map(r=>`<li><a href="#opportunity/${e(r.id)}">${e(r.title)}</a><br>${e(r.start?dateLabel(r.start,true):'Contact the organizer for arrangements')} · ${e(eventState(r))}${stale(r)?' · Needs a fresh check':''}<br>${e(r.cost||'Cost not confirmed')}<br>${link(r.signup_url||r.source_url,'Organizer details / signup')}</li>`).join('')}</ul><p>${e(pin.venue.accuracy)} ${link(pin.venue.coordinate_source,'Location source')}</p>`;
}
export function communityMapHTML(rows,venues){
 const pins=communityPins(rows,venues),mapped=pins.reduce((n,p)=>n+p.events.length,0);
 return `<details class="map-shell community-map"><summary>See places on a map · ${mapped} of ${rows.length} listings located</summary><div><p>Map and list use the same filters. Points show approximate venues, not entrances or boundaries. Opportunities without a verified location stay in the list.</p>${mapped?`<button id="load-community-map" data-records="${e(JSON.stringify(rows.map(r=>r.id)))}">Load community map</button>`:'<p class="empty">No verified venue points for this selection. All matching opportunities are below.</p>'}<p class="fine">Loading the map contacts OpenStreetMap and the map-library provider. Your location is not requested.</p><div id="community-map-content"></div><details><summary>Venue sources & accuracy</summary><div>${pins.map(p=>`<p><b>${e(p.venue.name)}</b>: ${e(p.venue.accuracy)} ${link(p.venue.coordinate_source,'Coordinate source')} · checked ${dateLabel(p.venue.last_checked)}</p>`).join('')||'<p>Additional venue locations still need verification.</p>'}<a href="./data/venues.json" download>Download venue sources</a></div></details></div></details>`;
}
export function discoveryHTML(rows){
 return `<details class="section-space"><summary>Where we look for local activities</summary><div><p>Start with City-linked organizations, then check hosts directly. This is a selected guide, not complete business or event coverage. No paid placement. Missing listings do not mean nothing is happening.</p>${(rows||[]).map(r=>`<article class="source-row"><h3>${link(r.website,r.name)}</h3><p>${e(r.status)}</p><p class="fine">${e(r.gap)}</p><p>${r.city_source?link(r.city_source,'City referral'):'Supplementary discovery'}${r.events_url?' · '+link(r.events_url,'Organizer listings'):''}${r.social_url?' · '+link(r.social_url,'Official social account'):''} · Checked ${dateLabel(r.last_checked)}</p></article>`).join('')||'<p>The discovery registry could not load. Organizer links in the listings remain available.</p>'}<a href="./data/discovery.json" download>Download source coverage</a></div></details>`;
}
export function artHTML(){
 return `<section class="art-note"><p class="eyebrow">A local collection, a wider story</p><h2>Meet the art in our history.</h2><p>The Historical Society holds Edmonia Lewis’s marble sculpture of Gerrit and Ann Smith’s clasped hands. Its exhibition story is a starting point for discovering an artist’s work—not a claim that the piece is currently on view in Oneida.</p>${link('https://mchs1900.org/edmonia-lewis-exhibit/','Explore the Society’s Edmonia Lewis story')}<p class="fine">Artwork image permission has not been established; no reproduction is used here.</p></section>`;
}
export function historyHTML(data){
 return `<header class="intro"><p class="eyebrow">History of Oneida</p><h1 tabindex="-1">One place. Many stories.</h1><p>Start with the people whose name the city carries, then follow the rail depot, a religious experiment and the industries that shaped daily life.</p></header>
 <nav class="history-jumps" aria-label="History topics"><a href="#history/people">Oneida people</a><a href="#history/city">City origins</a><a href="#history/community">The Oneida Community</a><a href="#history/industry">Industry & memory</a></nav>
 <p class="notice">Three distinct subjects: the City of Oneida is a municipality; the Oneida Indian Nation is a living sovereign nation; the nineteenth-century Oneida Community was a religious communal society.</p>
 <div class="history-layout"><div class="timeline">
 <section id="history-people"><p class="eyebrow">An enduring presence</p><h2>The people behind the name</h2><p>Oneida refers to the Oneida people, whose homelands long predate the city. The Oneida Indian Nation describes itself as Onyota’a:ká—People of the Standing Stone—and a founding member of the Haudenosaunee Confederacy. Its history continues through living language, culture and government.</p><p>The shared name does not make the Nation a City department or connect its beliefs to the later Oneida Community.</p>${link('https://www.oneidaindiannation.com/milestone/origins','Read the Nation’s account of its origins')}</section>
 <section id="history-city"><p class="eyebrow">1800s · A depot becomes a city</p><h2>Rail connections changed the place</h2><p>Madison County’s historian traces Oneida Depot’s growth to Sands Higinbotham’s land and a passenger stop on the Syracuse and Utica Railroad. The village incorporated in 1848, became a separate town in 1896, and received its city charter in 1901.</p><p>That municipal story is separate from the religious community founded nearby in 1848. Railway commerce, homes and local businesses helped shape a city larger than any single institution.</p>${link('https://www.madisoncounty.ny.gov/328/Oneida','County historian: Oneida’s development')}</section>
 <section id="history-community"><p class="eyebrow">1848–1880 · A communal experiment</p><h2>Life in the Oneida Community</h2><p>John Humphrey Noyes and his followers pursued Christian Perfectionism: the belief that people could live free from sin. Members shared property, work and childrearing. Their “complex marriage” treated members as married to the group rather than as exclusive couples.</p><p>Communal life challenged conventional marriage and domestic roles. It also placed intimate decisions under community authority. These tensions matter when discussing its promises of freedom.</p>${link('https://www.oneidacommunity.org/our-history','Mansion House: beliefs and communal life')} · ${link('https://www.nps.gov/articles/utopias-in-america.htm','National Park Service: American utopias')}
 <details><summary>Relationships, authority & controversy</summary><div><p>The Community’s selective-breeding program, called “stirpiculture,” chose parents for supposedly desirable intellectual, physical and spiritual traits. Historian Martin Richards examines its religious foundations, arranged reproduction and relationship to later eugenics.</p><p>Claims that people could be bred toward perfection should be read critically. This history raises questions about reproductive autonomy and the power of leaders over family life. “Free-love cult” alone does not explain those practices or their consequences.</p>${link('https://pubmed.ncbi.nlm.nih.gov/15468508/','Martin Richards, Perfecting People (2004), pp. 47–71')}</div></details></section>
 <section id="history-industry"><p class="eyebrow">1881 onward · Work and memory</p><h2>From shared enterprise to silverware</h2><p>The Community operated businesses making animal traps, silk goods and silverware. After communal life ended, a joint-stock company followed in 1881. Its connection to Oneida Ltd. is an industrial legacy, distinct from the City’s government and the Oneida Indian Nation.</p>${link('https://www.oneidacommunity.org/our-history','Mansion House: transition to a company')} · ${link('https://www.oneidacommunity.org/oneida-ltd-history','Explore factory films and workers’ oral histories')}
 <p>For another view of everyday local life, Cottage Lawn houses the Madison County Historical Society. The City Historian and library help residents explore local records and their own questions.</p>${link('https://mchs1900.org/','Visit the Historical Society')} · ${link('https://www.oneidacityny.gov/government/city_historian.php','Contact the City Historian')}</section></div>
 <aside class="history-images">${photoHTML(data.media,'mansion')}${photoHTML(data.media,'hall')}<p><a href="#community?type=History">Find a history visit or volunteer opportunity →</a></p></aside></div>
 ${artHTML()}<details class="section-space"><summary>Sources, image rights & further reading</summary><div><p>This introductory account uses the Nation’s own history, local public historians, the Mansion House museum and published scholarship. It is not a comprehensive history. Sources checked September 14, 2026.</p><p>Photographs are documentary views taken in 2020 and 2016, not evidence of present-day conditions. Credits and licenses accompany each image. They are resized without cropping.</p><a href="./data/media.json" download>Download image credits & rights</a><p>City, library, museum and artist website images require their own rights review. Edmonia Lewis artwork is linked, not reproduced. Contemporary artist features need a verified artist source and written permission or a suitable license.</p></div></details>`;
}
